version: '3.8'
services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.api
    environment:
      - MONGO_URI=mongodb://mongo:27017/markit
      - PORT=4000
    ports:
      - '4000:4000'
    depends_on:
      - mongo
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.web
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - api
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
